In [8]:
import pandas as pd
import numpy as np
import pymysql
import sqlalchemy as alch


import os 
from dotenv import load_dotenv
from getpass import getpass

import pprint

In [2]:
token = getpass()

In [3]:
madrid = pd.read_csv("C:/Users/Marco/Desktop/IronHack/projects/Project-SQL-Tableau/data/houses_Madrid.csv")

In [4]:
madrid

,Unnamed: 0,id,title,subtitle,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,...,energy_certificate,has_parking,has_private_parking,has_public_parking,is_parking_included_in_price,parking_price,is_orientation_north,is_orientation_west,is_orientation_south,is_orientation_east
0,0,21742,"Piso en venta en calle de Godella, 64","San Cristóbal, Madrid",64.0,60.0,2,1.0,NaN,NaN,...,D,False,NaN,NaN,NaN,NaN,False,True,False,False
1,1,21741,Piso en venta en calle de la del Manojo de Rosas,"Los Ángeles, Madrid",70.0,NaN,3,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,21740,"Piso en venta en calle del Talco, 68","San Andrés, Madrid",94.0,54.0,2,2.0,NaN,NaN,...,no indicado,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,21739,Piso en venta en calle Pedro Jiménez,"San Andrés, Madrid",64.0,NaN,2,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,False,False,True,False
4,4,21738,Piso en venta en carretera de Villaverde a Val...,"Los Rosales, Madrid",108.0,90.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21737,21737,5,Ático en venta en Casco Histórico de Barajas,"Barajas, Madrid",78.0,NaN,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21738,21738,4,Piso en venta en Urb. Campo de las Naciones - ...,"Barajas, Madrid",96.0,83.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,False,True,True,True
21739,21739,3,Piso en venta en Campo de las Naciones-Corralejos,"Barajas, Madrid",175.0,NaN,4,2.0,NaN,NaN,...,E,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21740,21740,2,"Chalet adosado en venta en calle Burriana, 12","Campo de las Naciones-Corralejos, Madrid",289.0,NaN,4,3.0,3.0,304.0,...,en trámite,True,NaN,NaN,True,0.0,False,False,True,False
21741,21741,1,"Piso en venta en calle San Epifanio, 9","Imperial, Madrid",72.0,NaN,2,2.0,NaN,NaN,...,A,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN

In [9]:
null_values = madrid.isnull().sum()

pprint.pprint(null_values)

Unnamed: 0                          0
id                                  0
title                               0
subtitle                            0
sq_mt_built                       126
sq_mt_useful                    13514
n_rooms                             0
n_bathrooms                        16
n_floors                        20305
sq_mt_allotment                 20310
latitude                        21742
longitude                       21742
raw_address                      5465
is_exact_address_hidden             0
street_name                      5905
street_number                   15442
portal                          21742
floor                            2607
is_floor_under                   1170
door                            21742
neighborhood_id                     0
operation                           0
rent_price                          0
rent_price_by_area              21742
is_rent_price_known                 0
buy_price                           0
buy_price_by_area                   0
is_buy_price_known                  0
house_type_id                     391
is_renewal_needed                   0
is_new_development                992
built_year                      11742
has_central_heating              8134
has_individual_heating           8134
are_pets_allowed                21742
has_ac                          10531
has_fitted_wardrobes             8343
has_lift                         2386
is_exterior                      3043
has_garden                      20186
has_pool                        16571
has_terrace                     12194
has_balcony                     18421
has_storage_room                14044
is_furnished                    21742
is_kitchen_equipped             21742
is_accessible                   17668
has_green_zones                 17685
energy_certificate                  0
has_parking                         0
has_private_parking             21742
has_public_parking              21742
is_parking_included_in_price    14023
parking_price                   14023
is_orientation_north            10384
is_orientation_west             10384
is_orientation_south            10384
is_orientation_east             10384
dtype: int64

In [11]:
null_values = madrid.isnull().sum()
null_columns = null_values[null_values > 0]
print(null_columns)

sq_mt_built                       126
sq_mt_useful                    13514
n_bathrooms                        16
n_floors                        20305
sq_mt_allotment                 20310
latitude                        21742
longitude                       21742
raw_address                      5465
street_name                      5905
street_number                   15442
portal                          21742
floor                            2607
is_floor_under                   1170
door                            21742
rent_price_by_area              21742
house_type_id                     391
is_new_development                992
built_year                      11742
has_central_heating              8134
has_individual_heating           8134
are_pets_allowed                21742
has_ac                          10531
has_fitted_wardrobes             8343
has_lift                         2386
is_exterior                      3043
has_garden                      20186
has_pool                        16571
has_terrace                     12194
has_balcony                     18421
has_storage_room                14044
is_furnished                    21742
is_kitchen_equipped             21742
is_accessible                   17668
has_green_zones                 17685
has_private_parking             21742
has_public_parking              21742
is_parking_included_in_price    14023
parking_price                   14023
is_orientation_north            10384
is_orientation_west             10384
is_orientation_south            10384
is_orientation_east             10384
dtype: int64

In [12]:
non_null_count = madrid.count()

print(non_null_count)

Unnamed: 0                      21742
id                              21742
title                           21742
subtitle                        21742
sq_mt_built                     21616
sq_mt_useful                     8228
n_rooms                         21742
n_bathrooms                     21726
n_floors                         1437
sq_mt_allotment                  1432
latitude                            0
longitude                           0
raw_address                     16277
is_exact_address_hidden         21742
street_name                     15837
street_number                    6300
portal                              0
floor                           19135
is_floor_under                  20572
door                                0
neighborhood_id                 21742
operation                       21742
rent_price                      21742
rent_price_by_area                  0
is_rent_price_known             21742
buy_price                       21742
buy_price_by_area               21742
is_buy_price_known              21742
house_type_id                   21351
is_renewal_needed               21742
is_new_development              20750
built_year                      10000
has_central_heating             13608
has_individual_heating          13608
are_pets_allowed                    0
has_ac                          11211
has_fitted_wardrobes            13399
has_lift                        19356
is_exterior                     18699
has_garden                       1556
has_pool                         5171
has_terrace                      9548
has_balcony                      3321
has_storage_room                 7698
is_furnished                        0
is_kitchen_equipped                 0
is_accessible                    4074
has_green_zones                  4057
energy_certificate              21742
has_parking                     21742
has_private_parking                 0
has_public_parking                  0
is_parking_included_in_price     7719
parking_price                    7719
is_orientation_north            11358
is_orientation_west             11358
is_orientation_south            11358
is_orientation_east             11358
dtype: int64

In [13]:
non_null_columns = non_null_count[non_null_count == len(madrid)]
print(non_null_columns)

Unnamed: 0                 21742
id                         21742
title                      21742
subtitle                   21742
n_rooms                    21742
is_exact_address_hidden    21742
neighborhood_id            21742
operation                  21742
rent_price                 21742
is_rent_price_known        21742
buy_price                  21742
buy_price_by_area          21742
is_buy_price_known         21742
is_renewal_needed          21742
energy_certificate         21742
has_parking                21742
dtype: int64

In [18]:
columns_with_nulls = madrid.columns[madrid.isnull().any()]
null_counts = madrid[columns_with_nulls].isnull().sum().sort_values(ascending=False)

print("Columns with the most null values:")
print(null_counts)

Columns with the most null values:
rent_price_by_area              21742
is_furnished                    21742
latitude                        21742
longitude                       21742
has_private_parking             21742
has_public_parking              21742
portal                          21742
is_kitchen_equipped             21742
are_pets_allowed                21742
door                            21742
sq_mt_allotment                 20310
n_floors                        20305
has_garden                      20186
has_balcony                     18421
has_green_zones                 17685
is_accessible                   17668
has_pool                        16571
street_number                   15442
has_storage_room                14044
parking_price                   14023
is_parking_included_in_price    14023
sq_mt_useful                    13514
has_terrace                     12194
built_year                      11742
has_ac                          10531
is_orientation_north            10384
is_orientation_west             10384
is_orientation_south            10384
is_orientation_east             10384
has_fitted_wardrobes             8343
has_individual_heating           8134
has_central_heating              8134
street_name                      5905
raw_address                      5465
is_exterior                      3043
floor                            2607
has_lift                         2386
is_floor_under                   1170
is_new_development                992
house_type_id                     391
sq_mt_built                       126
n_bathrooms                        16
dtype: int64

In [22]:
21742 / 2

10871.0